# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_image', models.ImageField(upload_to='projects/')),
                ('project_description', tinymce.models.HTMLField()),
                ('live_link', url_or_relative_url_field.fields.URLOrRelativeURLField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
