# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-29 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_image', models.ImageField(upload_to='projects/')),
                ('project_description', tinymce.models.HTMLField()),
                ('live_link', models.URLField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
