# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-30 09:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usability_vote', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('design_vote', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('content_vote', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('average_vote', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('project_id', models.IntegerField(default=0)),
                ('voter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
